--ATIVIDADE A
SELECT PRODUTO, VALOR,CATEGORIA 
FROM VENDAS
WHERE VALOR >(
   SELECT MIN(VALOR) FROM VENDAS WHERE CATEGORIA ='Eletrônicos' 
);

--ATIVIDADE B
SELECT PRODUTO,VALOR, VENDEDOR 
WHERE valor = (SELECT MAX(valor) FROM VENDAS);

--ATIVIDADE C
SELECT DISTINCT categoria,PRODUTO,VALOR
FROM VENDAS v
WHERE valor > (SELECT AVG(valor) FROM VENDAS);

--ATIVIDADE D
SELECT *
FROM (
    SELECT
        vendedor,
        produto,
        valor,
        ROW_NUMBER() OVER (PARTITION BY vendedor ORDER BY valor DESC) AS ranking
    FROM VENDAS
) t
WHERE ranking <= 3;
